### ISSUE TITLE
Unknown command repro_zip_latex with `RepRepBuild==1.7.0`

### ISSUE THREAD

**Issue by yingxingcheng** [reproducible-reporting/reprepbuild#28]
Hi Toon,

I've got some errors when I try to use the latest version of `RepRepBuild`.

```
Traceback (most recent call last):
  File "/Users/yingxing/Projects/empty-project/venv/bin/rr", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/yingxing/Projects/empty-project/venv/lib/python3.12/site-packages/reprepbuild/__main__.py", line 161, in main
    generate(os.getcwd())
  File "/Users/yingxing/Projects/empty-project/venv/lib/python3.12/site-packages/reprepbuild/__main__.py", line 54, in generate
    load_config(root, "reprepbuild.yaml", generators)
  File "/Users/yingxing/Projects/empty-project/venv/lib/python3.12/site-packages/reprepbuild/config.py", line 256, in load_config
    raise ValueError(f"In {path_config}, unknown command: {command_name}")
ValueError: In reprepbuild.yaml, unknown command: repro_zip_latex
```

Packages installed (`pip list`):
```
Package            Version
------------------ -----------
attrs              23.1.0
beautifulsoup4     4.12.2
BibSane            0.1.3
bibtexparser       1.4.1
Brotli             1.1.0
cattrs             23.2.2
certifi            2023.11.17
cffi               1.16.0
cfgv               3.3.1
charset-normalizer 3.3.2
colorama           0.4.6
contourpy          1.2.0
cssselect2         0.7.0
cycler             0.12.1
distlib            0.3.7
exceptiongroup     1.2.0
filelock           3.13.1
fonttools          4.45.1
html5lib           1.1
identify           2.5.32
idna               3.6
iniconfig          2.0.0
Jinja2             3.1.2
kiwisolver         1.4.5
Markdown           3.5.1
markdown-katex     202112.1034
MarkupSafe         2.1.3
matplotlib         3.8.2
munkres            1.1.4
ninja              1.11.1.1
nodeenv            1.8.0
numpy              1.26.2
packaging          23.2
parse              1.20.0
pathlib2           2.3.7.post1
Pillow             10.1.0
pip                23.3.1
platformdirs       4.0.0
pluggy             1.3.0
pre-commit         3.5.0
pycparser          2.21
pydyf              0.8.0
PyMuPDF            1.21.1
pyparsing          3.1.1
pyphen             0.14.0
pytest             7.4.3
python-dateutil    2.8.2
PyYAML             6.0.1
RepRepBuild        1.7.0
requests           2.31.0
scipy              1.11.4
setuptools         68.2.2
six                1.16.0
soupsieve          2.5
tinycss2           1.2.1
tomli              2.0.1
tornado            6.3.3
tqdm               4.66.1
typing_extensions  4.8.0
ukkonen            1.0.1
urllib3            2.1.0
virtualenv         20.24.7
watchdog           3.0.0
weasyprint         60.1
webencodings       0.5.1
wheel              0.42.0
zopfli             0.2.3
```

Other potential issues:

- Also, the default version of `RepRepBuild` is `1.5.0` in `templates` and I think it should be updated as well.
- `Swig` should be installed before installing PyMuPDF. (Solution from GPT: https://chat.openai.com/share/cd35a451-f3c4-4bee-a362-ac011bc64d3f)

**Comment by tovrstra** [comment]
Sorry for that. A few commands were renamed, see CHANGELOG.md

Things should be better with the current version of PyMuPDF (one was released today). The new versions are distributed with compiled extensions. To avoid that old files hang around, it is best to uninstall the old PyMuPDF first:

```bash
pip uninstall PyMuPDF PyMuPDFb
pip install PyMuPDF PyMuPDFb
```

This should give you version 1.23.7. I will make a release of RepRepBuild soon that works well with this version. (See latest commit.)

**Comment by yingxingcheng** [comment]
JPG file is not added becuase it is ignored by `.gitignore`

```
# LaTeX
*/latex-*/*.aux
*/latex-*/*.log
*/latex-*/*.fls
*/latex-*/*.toc
*/latex-*/*.fdb_latexmk
*/latex-*/*.latexmk
*/latex-*/*.bbl
*/latex-*/*.blg
*/latex-*/*.nlo
*/latex-*/*.out
*/latex-*/*.pdf
*/latex-*/*.jpeg
*/latex-*/*.jpg
*/latex-*/*.png
*/latex-*/*.tiff
*/latex-*/*.tif
*/latex-*/*-diff.*
*/latex-*/*.synctex*
!*/latex-*/*-old.*
*/uploads/*.zip
*/uploads/*.pdf
*/latex-*/acs-*.bib
*/latex-*/*Notes.bib
*/latex-*/*.sha256

# Software environment
venv

# Ninja and RepRepBuild
.ninja_log
.ninja_deps
build.ninja
*.dd
*.d
.reprepbuild
*/latex-article/article.tex

# Python
__pycache__
dist
build

# Scripts
*/results-*/*.log

```

**Comment by tovrstra** [comment]
Sorry for that, I forgot to push.

**Comment by yingxingcheng** [comment]
Yes, it works properly now. Feel free to close the issue.

**Comment by tovrstra** [comment]
Thanks for checking.
